// <auto-generated />
namespace RaportowanieSprzedazy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ZamianaZWieluNaJedenOdpowiedzPracownik : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZamianaZWieluNaJedenOdpowiedzPracownik));
        
        string IMigrationMetadata.Id
        {
            get { return "201812292323390_ZamianaZWieluNaJedenOdpowiedzPracownik"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
